services:
  - type: web
    name: checklist-splitter
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_SERVER
        value: smtp.mail.yahoo.com
      - key: SMTP_PORT
        value: 587
      - key: CONTACT_EMAIL
        value: ryanyounker@ymail.com
      - key: ADMIN_KEY
        sync: false
